/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Lagst (https://sketchfab.com/Lagst)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/robot-435566387be94cbfbc623c3d45241769
Title: Robot
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

function Developer(props:any) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/humans/robot333.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="562ea4e4dc1c46e7a30707eb27f445c6fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_220"
                      geometry={nodes.Object_220.geometry}
                      material={materials.material}
                      skeleton={nodes.Object_220.skeleton}
                    />
                    <group name="Object_219" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                  </group>
                </group>
                <group name="Bot" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/humans/robot333.glb')


export default Developer

