/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: _SeF_ (https://sketchfab.com/_SeF_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robo-v2-133f1c7254a04031b98ea9a30b27728a
Title: Robo_V2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    [key: string]: THREE.Mesh
  }
  materials: {
    [key: string]: THREE.Material
  }
}

function Robo(props:any) {
  const { nodes, materials } = useGLTF('/models/robo.gltf') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        position={[-190.232, 76.195, 174.651]}
        rotation={[-1.745, 0, 0]}
        scale={[0.559, 0.55, 0.222]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object040_Material_#1573_0'].geometry}
          material={materials.Material_1573}
          position={[-2.391, -5.046, -0.571]}
        />
      </group>
      <group
        position={[-190.232, 76.195, 174.651]}
        rotation={[-1.745, 0, 0]}
        scale={[0.559, 0.55, 0.222]}>
        <group position={[-2.391, -5.046, -0.571]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#1601_0'].geometry}
            material={materials.Material_1601}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#1602_0'].geometry}
            material={materials.Material_1602}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#1626_0'].geometry}
            material={materials.Material_1626}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#1651_0'].geometry}
            material={materials.Material_1651}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#1676_0'].geometry}
            material={materials.Material_1676}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#2106_0'].geometry}
            material={materials.Material_2106}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#1881_0'].geometry}
            material={materials.Material_1881}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_01_-_Default_0'].geometry}
            material={materials['01_-_Default']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#1627_0'].geometry}
            material={materials.Material_1627}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#5503_0'].geometry}
            material={materials.Material_5503}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#2155_0'].geometry}
            material={materials.Material_2155}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#1652_0'].geometry}
            material={materials.Material_1652}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#1628_0'].geometry}
            material={materials.Material_1628}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#1573_0'].geometry}
            material={materials.Material_1573}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#1625_0'].geometry}
            material={materials.Material_1625}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object041_steel_02_03_0.geometry}
            material={materials.steel_02_03}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object041_steel_02_02_0.geometry}
            material={materials.steel_02_02}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object041_steel_02_01_0.geometry}
            material={materials.steel_02_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object041_wire_02_0.geometry}
            material={materials.wire_02}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#1882_0'].geometry}
            material={materials.Material_1882}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object041_svet_0.geometry}
            material={materials.svet}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#1856_0'].geometry}
            material={materials.Material_1856}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#5579_0'].geometry}
            material={materials.Material_5579}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#1917_0'].geometry}
            material={materials.Material_1917}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Object041_Material_#1675_0'].geometry}
            material={materials.Material_1675}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/robo.gltf')

export default Robo
